### PR TITLE
Password validation for Identity provider

### LINKED ISSUE #36: Password update logs users in when form is not completed
When completing the update password form using the link emailed to you, if you leave the password fields blank and submit the form you will be logged in and redirected to the after login path.  Your password is not updated, but the form behaves as though you completed it successfully and you are then logged in.

When leaving the password and password confirmation fields blank you should remain logged out and be returned to the form (and ideally provided with messaging about completing the fields).

### PR DESCRIPTION
**Pull request by phlipper**
- fixes #36

### CODE REVIEW

**Comment by kjohnston** [comment]
This looks great.  I took it for a test drive and confirmed it resolves the issue in the app we're working on.  Travis is failing for rbx and 1.9.2 (mysql only) - is there something we need to do?

**Comment by phlipper** [comment]
@kjohnston both issues are addressed by #35

**Comment by kjohnston** [comment]
@phlipper, thanks, switching over there.

**Comment by kjohnston** [comment]
@phlipper, I merged #35, want to rebase this one?

**Comment by phlipper** [comment]
@kjohnston rebase complete.

**Comment by kjohnston** [comment]
@phlipper, merged.  Thanks for getting this knocked out so quickly.  Want to cut a new version?

**Comment by phlipper** [comment]
@kjohnston 0.6.1 has been cut.

**Pull request merged**
