### PR TITLE
Add ability to set session to remember the return path

### PR DESCRIPTION
**Pull request by mfpiccolo**
Set session[:return_to] if exists in the Sessions Controller new action.

### CODE REVIEW

**Comment by bousquet** [comment]
This deserves a test to illustrate use case and what happens with and without the referrer.

**Comment by elskwid** [comment]
I would argue that this doesn't belong in the gem but rather implemented in the application. It's a small matter of `after_login_path`, right?

**Comment by mfpiccolo** [comment]
Ya. Sorry about that guys.  I was unaware that a pr from a fork sent it to the main repo.

**Comment by mfpiccolo** [comment]
I pushed up my branch after-login-persistence to classic.  This was the only way I could get it to work but I would be grateful for any advice on a better way.

**Comment by mfpiccolo** [comment]
Keep experimenting with this and try to find a way to do it within the app.  May be interested in exploring a way for the gem to handle it if others run into this issue.

**Pull request closed without merging**
