### PR TITLE
Add methods for post login/registration redirects.

### PR DESCRIPTION
**Pull request by kjohnston**
Adds methods for post-login, post-logout and post-register paths.
- Paths default to root URL as they did before.
- A separate method is provided for each path for easy overriding.

### CODE REVIEW

**Comment by phlipper** [comment]
@kjohnston can you bump the test coverage back up to 100% please? Thanks :heart:

**Comment by kjohnston** [comment]
@phlipper, tests added, back to 100.0%.

**Comment by phlipper** [comment]
@kjohnston :+1: Thanks!

**Comment by phlipper** [comment]
@kjohnston can you submit another pull request with an update to the README describing this new feature? Thanks!

**Pull request merged**
